[package]
name = "scraper"
version = "0.1.0"
authors = ["a"]

[dependencies]
futures = "0.1"
futures-cpupool = "0.1"
tokio-core = "0.1"
#tokio-io = "0.1"
hyper = "0.11"
hyper-tls = "0.1"
log = "0.4"
lazy_static = "1.0"
clippy = "*"
